name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Sync dependencies
        run: uv sync --frozen

      - name: Build site
        run: uv run mkdocs build --verbose --clean

      - name: Deploy to user site
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}
          external_repository: slavadubrov/slavadubrov.github.io
          publish_branch: main
          publish_dir: ./site
